### ISSUE TITLE
If a low confidence score means that the obtained mapped_rxn is invalid and can not use it? 

### ISSUE THREAD

**Issue by queliyong** [rxn4chemistry/rxnmapper#11]
Hi, I got my mapped_rxn results with low confidence scores, among 0.2~0.8. Does it mean that I can not use those results with too low score?

**Comment by pschwllr** [comment]
It is hard to say without seeing the reactions. If I were you I would manually check some of the atom-maps, maybe   the atom-maps still make sense and there is a simple reason for the low confidence.

**Comment by queliyong** [comment]
> It is hard to say without seeing the reactions. If I were you I would manually check some of the atom-maps, maybe the atom-maps still make sense and there is a simple reason for the low confidence.

Thanks for your advice.
