### ISSUE TITLE
 AttributeError: 'SmilesTokenizer' object has no attribute 'max_l

### ISSUE THREAD

**Issue by Long-TA** [rxn4chemistry/rxnmapper#13]
Hi,

I got this problem when trying to run the example

```
Traceback (most recent call last):
  File "atom_mapping.py", line 2, in <module>
    rxn_mapper = RXNMapper()
  File "C:\Users\tangu\anaconda3\lib\site-packages\rxnmapper\core.py", line 65, in __init__
    self.model, self.tokenizer = self._load_model_and_tokenizer()
  File "C:\Users\tangu\anaconda3\lib\site-packages\rxnmapper\core.py", line 91, in _load_model_and_tokenizer
    tokenizer = SmilesTokenizer(
  File "C:\Users\tangu\anaconda3\lib\site-packages\rxnmapper\tokenization_smiles.py", line 45, in __init__
    self.max_len_single_sentence = self.max_len - 2
AttributeError: 'SmilesTokenizer' object has no attribute 'max_len
```
Please help to solve it,

Thank you!

**Comment by Long-TA** [comment]
That is the error I got when I set up the package through pip
I update the latest version from GitHub and the problem solved

**Comment by Long-TA** [comment]
I got this problem when using version from pip
I updated github version, the problem solved now.

**Comment by YH-88** [comment]
Hello,
I'm having the same problem. Did you install it through GitHub or PIP?I have the following problems when installing on GitHub. Could you please tell me the specific installation process?
![image](https://user-images.githubusercontent.com/56984869/124551884-5c81b680-de65-11eb-8b5d-0b0e50ebcbc6.png)

**Comment by Long-TA** [comment]
You should install rdkit https://www.rdkit.org/docs/Install.html

**Comment by YH-88** [comment]
Hello,
I'm having the same problem. Did you install it through GitHub or PIP?I have the following problems when installing on GitHub. Could you please tell me the specific installation process?
![image](https://user-images.githubusercontent.com/56984869/124551884-5c81b680-de65-11eb-8b5d-0b0e50ebcbc6.png)

**Comment by YH-88** [comment]
Thanks a lot. But how do you specify a specific version?I'm running on Windows now, does that matter?Also, did you clone the code directly and then run the rest of the code directly in Windows PowerShell.
