### ISSUE TITLE
Request: All source code to reproduce will be contained in this repository? 

### ISSUE THREAD

**Issue by tsnguyen05** [rxn4chemistry/rxnmapper#15]
Greetings,

Some of the reactions cannot be matched correctly, and they need some special modifications (I have tried on Indigo and it did not work either). In order to understand how the process works, may I ask whether all codes are published and stored in this repository so that I can request to look at them in detail, if possible? 

If so, may I also ask whether they would be in the "rxnmapper" folder only and neither in "docs" nor "docs_source" by chance?

Thank you,
Tommy

**Comment by pschwllr** [comment]
Yes, the rxnmapper folder contains the code to reproduce the results of the paper.
