### ISSUE TITLE
False atom mapping result.

### ISSUE THREAD

**Issue by queliyong** [rxn4chemistry/rxnmapper#16]
Hi, 
Considering mapping this reaction:
'C=CC(C=C)C(O)C23CC1CC(CC(C1)C2)C3>>C=CC(C=C)C(Br)C23CC1CC(CC(C1)C2)C3'
It gives:
'O[CH:6]([CH:3]([CH:2]=[CH2:1])[CH:4]=[CH2:5])[C:8]12[CH2:9][CH:10]3[CH2:11][CH:12]([CH2:13][CH:14]([CH2:15]3)[CH2:16]1)[CH2:17]2>>[CH2:1]=[CH:2][CH:3]([CH:4]=[CH2:5])[CH:6]([Br:7])[C:8]12[CH2:9][CH:10]3[CH2:11][CH:12]([CH2:13][CH:14]([CH2:15]3)[CH2:16]1)[CH2:17]2'
![image](https://user-images.githubusercontent.com/56716710/130049114-f296c034-80c3-44a4-9f9b-a05dc7ad3236.png)

It seems the Br atom is incorrectly mapped, thank you very much for your help.

**Comment by pschwllr** [comment]
<img width="726" alt="image" src="https://user-images.githubusercontent.com/38880871/130059071-442d8dca-2165-4fa3-a002-d8d09e3ac352.png">

What would you like to see? No atom-mapping number for the Br atom?

If there is a Br atom on the in the reactants the product Br will be mapped to that Br atom. 

<img width="554" alt="image" src="https://user-images.githubusercontent.com/38880871/130059353-0afa5bef-fe38-4c67-bccf-aa636f43f677.png">

**Comment by queliyong** [comment]
> <img alt="image" width="726" src="https://user-images.githubusercontent.com/38880871/130059071-442d8dca-2165-4fa3-a002-d8d09e3ac352.png">
> 
> What would you like to see? No atom-mapping number for the Br atom?
> 
> If there is a Br atom on the in the reactants the product Br will be mapped to that Br atom.
> 
> <img alt="image" width="554" src="https://user-images.githubusercontent.com/38880871/130059353-0afa5bef-fe38-4c67-bccf-aa636f43f677.png">

Thanks a lot, I see.
