### ISSUE TITLE
what's the value of the per_gpu_train_batch_size in the process of  trainning the model?

### ISSUE THREAD

**Issue by autodataming** [rxn4chemistry/rxnmapper#3]
```py
training_args = TrainingArguments(
    output_dir="./",
    overwrite_output_dir=True,
    num_train_epochs=5,
    per_gpu_train_batch_size=8,  
    save_steps=10_000,
    save_total_limit=2,
)
```

what's the value of the per_gpu_train_batch_size when train the model?

**Comment by pschwllr** [comment]
We used `16` as `per_gpu_train_batch_size` and trained on a single GPU.

**Comment by autodataming** [comment]
> 
> 
> We used `16` as `per_gpu_train_batch_size` and trained on a single GPU.
Thank you!

How many of P100 GPU cards you used? 

I have 4 p100 cards, when I set the value to 16,it will raise "out of gpu memory".
