### ISSUE TITLE
if the atom mapping is invalid, should we remove this reaction when trainning model?

### ISSUE THREAD

**Issue by yangxfei** [rxn4chemistry/rxnmapper#45]
Hello, if with rxnmapper adding atom mapping, the reaction 's atom mapping is invalid or the confidence score is low, should I discard this reaction while trainning model?

with rdkit, we could validate if the atom mapping is valid or not, i am not sure if I should filter out all the invalid reaction with invalid atom mapping.  Thanks.

**Comment by avaucher** [comment]
Hi @yangxfei, 
I guess this is mainly up to you. It is possible that some reactions for which the atom mapping is incorrect or has low confidence are actually correct; we haven't investigated that.

**Comment by yangxfei** [comment]
thanks, @avaucher ,I got it.
