### ISSUE TITLE
Dubious mapping case

### ISSUE THREAD

**Issue by parit** [rxn4chemistry/rxnmapper#48]
Hello,

I am mapping a reaction smiles as follows:

`smiles = "[O-][Cl]=O>>[Cl-].O=O"; 
RXNMapper().get_attention_guided_atom_maps([smiles])
`

and the mapped smiles are 

`[O-:1][Cl+:3][O-:2]>>[O:1]=[O:2].[Cl-:3]`

why is the =O in the substrate broken in the mapped smiles? 

https://www.rhea-db.org/rhea/21406

**Comment by avaucher** [comment]
This is likely because the reaction is canonicalized by default. See [here](https://github.com/rxn4chemistry/rxnmapper/blob/90a7012c9c0127f4a347baf815e270d8807b5a39/tests/test_mapper.py#L68) for an example with no canonicalization
