### ISSUE TITLE
Rdkit coordination "->" after SMILES sanitization creates invalid reaction

### ISSUE THREAD

**Issue by frederik-sandfort1** [rxn4chemistry/rxnmapper#50]
RDKit changed it's behavior to display coordination of metal ions (e.g. carboxylate cations). As this includes a "->", it is incompatible with rxnmappers splitting of the reaction at ">" (see [here](https://github.com/rxn4chemistry/rxnmapper/blob/main/rxnmapper/smiles_utils.py#L467)).

Example for Reaction sanitization:
```python
from rdkit.Chem import AllChem
smi = "COC(=O)CCBr.O=C([O-][K+])c1ccccc1>>COC(=O)CCOC(=O)Cc1ccccc1"
rxn = AllChem.ReactionFromSmarts(smi, useSmiles=True)
AllChem.SanitizeRxnAsMols(rxn)
print(AllChem.ReactionToSmiles(rxn))
>>> "COC(=O)CCBr.O=C([O-]->[K+])c1ccccc1>>COC(=O)CCOC(=O)Cc1ccccc1"
```

Example for molecule sanitization:
```python
from rdkit import Chem
smi = "COC(=O)CCBr.O=C([O-][K+])c1ccccc1>>COC(=O)CCOC(=O)Cc1ccccc1"
components = smi.split(">")
[Chem.MolToSmiles(Chem.MolFromSmiles(component)) for component in components]
>>> ['COC(=O)CCBr.O=C([O-]->[K+])c1ccccc1', '', 'COC(=O)CCOC(=O)Cc1ccccc1']
```

While likely the "->" is not in the vocab (and thus not compatible with the current model version), you could just check for the sign and replace it with an empty string, to stay compatible with the sanitization.
Additionally, it could make sense to use rdkits `rxn.GetReactants()`, `rxn.GetAgents()` and `rxn.GetProducts()` function instead of the string splitting.

Just wanted to make you aware of this issue.
Best
Frederik

@avaucher

**Comment by avaucher** [comment]
Hi Frederik, 

Thanks for reporting this. Such reaction SMILES should now work with the new version of `rxn-chemutils` (see change in https://github.com/rxn4chemistry/rxn-chemutils/pull/30). In #53, I added a test to confirm.

Note that although it technically works, the current model was not trained on a single reaction containing such dative bonds :)

**Comment by frederik-sandfort1** [comment]
@avaucher thank you so much for implementing. I will check on our examples as well.

Also thanks for the note - I am aware of this and likely will keep the current workflow for removing the dative bonds :)
