### ISSUE TITLE
Question on maintenance

### ISSUE THREAD

**Issue by DavidWalz** [rxn4chemistry/rxnmapper#51]
Dear @avaucher 

Do you plan to maintain this python package going forward?
There are a few changes, e.g. #50 and adaption to newer torch version that might be interesting to other users.

**Comment by avaucher** [comment]
Hi @DavidWalz,
I don't expect any active work for new features or new models, but I'll do my best to find time for patches. Feel free to file issues or PRs. #50 is now supported.
